name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Version In File Updater 
      uses: bhaumikmistry/Version-update-action@v0.2-alpha

      with:
        versionFileName: version.js
        versionNumberEncapsulateText: "*"
    - name: Update version.js
        run: |
          cat version.js
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add version.js
          git commit -am "updating version in version.js" ||  true
          git push --force origin HEAD:$GITHUB_REF || true    
