name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Version In File Updater 
      uses: bhaumikmistry/Version-update-action@v0.2-alpha
      with:
        versionFileName: version.js
        versionNumberEncapsulateText: "*"
      run: ls